function lab7() {
const head=document.createElement("h1");
head.innerText="Lab7 Assignment";
head.style.color = "orange";
head.setAttribute("id", "title");
document.body.appendChild(head);
document.getElementById("title").setAttribute("style", "color: blue;");
const hr = document.createElement("hr");
head.appendChild(hr);
var h1 = document.querySelector('h1');
h1.parentNode.removeChild(h1);
let h2=document.createElement("h2");
h2.innerText="Task";
h2.style.color = "red";
document.body.appendChild(h2);
const p1=document.createElement("p");
p1.innerHTML = "In this task you have to reproduce this HTML page as is using <b>only</b> JavaScript. The task will be evaluated on the basis of the following DOM manipulation techniques:";
document.body.appendChild(p1);
var ul = document.createElement("ul");
var li1 = document.createElement("li");
li1.innerHTML = "find elements in the DOM (<b>5 points</b>)";
li1.classList.add("even");
ul.appendChild(li1);
var li2 = document.createElement("li");
li2.innerHTML = "create/add/remove elements (<b>5 points</b>)";
li2.classList.add("odd");
ul.appendChild(li2);
var li3 = document.createElement("li");
li3.innerHTML = "change content of the elements (<b>5 points</b>)";
li3.classList.add("even");
ul.appendChild(li3);
var li4 = document.createElement("li");
li4.innerHTML = "change styles of the elements (<b>5 points</b>)";
li4.classList.add("odd");
ul.appendChild(li4);
var li5 = document.createElement("li");
li5.innerHTML = "change attributes of the elements (<b>5 points</b>)";
li5.classList.add("even");
ul.appendChild(li5);
var li6 = document.createElement("li");
li6.innerHTML = "change classes of the elements (<b>5 points</b>)";
li6.classList.add("odd");
ul.appendChild(li6);
var style = document.createElement('style');
style.innerHTML = `
  .even {
    color: green;
  }
  .odd {
    color: purple;
  }`;
document.body.appendChild(ul);
document.head.appendChild(style);
document.body.appendChild(document.createElement("p").appendChild(document.createElement("hr")));
let h3=document.createElement("h2");
h3.innerText="Submission";
h3.style.color="red";
document.body.appendChild(h3);
const p3=document.createElement("p");
p3.innerHTML = "To submit your work, follow these instructions:";
document.body.appendChild(p3);
var ulb = document.createElement("ul");
var li1b = document.createElement("li");
li1b.innerHTML = "Create a new repository on Github, named <b>lab7</b> (<b>1 point</b>).";
li1b.classList.add("even");
ulb.appendChild(li1b);
var li2b = document.createElement("li");
li2b.innerHTML = "Clone this repository to your local machine and work inside it.";
li2b.classList.add("odd");
ulb.appendChild(li2b);
var li3b = document.createElement("li");
li3b.innerHTML = 'Create a new HTML file, called <b>index.html</b>, which has only one &lt;h1&gt; tag with "Hello, World!" message (<b>1 point</b>).';
li3b.classList.add("even");
ulb.appendChild(li3b);
var li4b = document.createElement("li");
li4b.innerHTML = "Create a new JavaScript file, called <b>main.js</b>, which must contain your program (assignment) described above (<b>1 point</b>).";
li4b.classList.add("odd");
ulb.appendChild(li4b);
var li5b = document.createElement("li");
li5b.innerHTML = "Link this <b>main.js</b> file to your <b>index.html</b> file (Note: place your script at the end of the <b>body</b> section).";
li5b.classList.add("even");
ulb.appendChild(li5b);
var li6b = document.createElement("li");
li6b.innerHTML = "Write a JavaScript program in <b>main.js</b> to make your <b>index.html</b> look identical to this HTML file (<b>5 points</b>).";
li6b.classList.add("odd");
ulb.appendChild(li6b);
var li7b = document.createElement("li");
li7b.innerHTML = "After you finish your work, submit it to the Github (<b>2 points</b>).";
li7b.classList.add("even");
ulb.appendChild(li7b);
document.body.appendChild(ulb);
const endHr = document.createElement("hr");
document.body.appendChild(document.createElement("p").appendChild(endHr));
}